import argparse
import json
import shutil
import subprocess
import sys
import uuid
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from PIL import Image, ImageOps

from backend_worker.nanobanana_client import (
    NanoBananaUsage,
    refine_with_nanobanana,
    simulate_refine,
)
from backend_worker.quality_gate import (
    GateDecision,
    evaluate_quality,
    evaluate_input_viability,
)


IMAGE_SIZE = (768, 1024)  # width, height


def _build_smart_prompt(quality) -> str:
    """
    품질 게이트 분석 결과를 바탕으로 NanoBanana에 보낼 정밀 프롬프트 생성.
    어떤 부분이 약한지 구체적으로 지시 → 1회 호출로 충분하게 만듦.
    """
    parts = [
        "This is a photo of a pet wearing clothes generated by AI."
    ]

    if quality.boundary_smoothness < 0.6:
        parts.append(
            "Fix the unnatural boundary between the clothing and the pet's body. "
            "Blend the edges smoothly so the clothing looks naturally worn."
        )

    if quality.color_consistency < 0.55:
        parts.append(
            "The clothing color and texture look inconsistent. "
            "Make the clothing fabric look realistic and maintain the original color."
        )

    if quality.boundary_smoothness >= 0.6 and quality.color_consistency >= 0.55:
        parts.append(
            "Slightly enhance overall quality: improve lighting, texture detail, "
            "and make it look like a real photograph."
        )

    parts.append(
        "Keep the pet's face, ears, paws, and tail exactly as they are. "
        "Do not change the pet's pose or the background."
    )

    return " ".join(parts)


def run_cmd(cmd, cwd=None):
    print("\n[RUN]", " ".join(str(x) for x in cmd), flush=True)
    subprocess.run(cmd, cwd=cwd, check=True)


def ensure_rgb_jpg(src: Path, dst: Path, resize_to=None):
    """
    업로드 이미지를 RGB JPG로 정리한다.
    PNG/RGBA도 흰 배경으로 변환한다.
    """
    img = Image.open(src)
    img = ImageOps.exif_transpose(img)

    if img.mode in ("RGBA", "LA"):
        bg = Image.new("RGB", img.size, (255, 255, 255))
        rgba = img.convert("RGBA")
        bg.paste(rgba, mask=rgba.split()[-1])
        img = bg
    else:
        img = img.convert("RGB")

    if resize_to is not None:
        img = img.resize(resize_to, Image.Resampling.BICUBIC)

    dst.parent.mkdir(parents=True, exist_ok=True)
    img.save(dst, quality=95)


def ensure_mask_png(src: Path, dst: Path, resize_to=None):
    img = Image.open(src).convert("L")

    if resize_to is not None:
        img = img.resize(resize_to, Image.Resampling.NEAREST)

    dst.parent.mkdir(parents=True, exist_ok=True)
    img.save(dst)


def write_test_json(path: Path, image_name: str, item_name: str):
    data = {
        "annotations": [
            {
                "file_name": image_name,
                "tag_info": [
                    {"tag_name": "sleeveLength", "tag_category": "short sleeve"},
                    {"tag_name": "neckLine", "tag_category": "round neck"},
                    {"tag_name": "item", "tag_category": item_name},
                ],
            }
        ]
    }

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def find_first_existing(paths):
    for p in paths:
        if p.exists():
            return p
    return None


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("--pet_image", required=True)
    parser.add_argument("--cloth_image", required=True)
    parser.add_argument("--output", required=True)

    parser.add_argument("--pet_type", default="auto", choices=["auto", "dog", "cat"])
    parser.add_argument("--item_name", default="pet sweater")

    parser.add_argument("--num_inference_steps", type=int, default=30)
    parser.add_argument("--guidance_scale", type=float, default=2.0)
    parser.add_argument("--seed", type=int, default=42)

    parser.add_argument("--project_root", default=str(PROJECT_ROOT))
    parser.add_argument(
        "--delta_checkpoint",
        default=None,
        help="Path to checkpoint-final-* folder. Default: <project_root>/output_pet_vton_delta_101/checkpoint-final-140",
    )

    parser.add_argument("--use_nanobanana", action="store_true",
                        help="Enable NanoBanana API refinement as the final step")
    parser.add_argument("--nanobanana_dry_run", action="store_true",
                        help="Simulate NanoBanana API call without actually calling it (cost estimation only)")
    parser.add_argument("--nanobanana_prompt", default=None,
                        help="Custom prompt for NanoBanana refinement")

    args = parser.parse_args()

    project_root = Path(args.project_root).expanduser().resolve()
    idm_dir = project_root / "IDM-VTON"

    if args.delta_checkpoint is None:
        delta_checkpoint = project_root / "output_pet_vton_delta_101" / "checkpoint-final-140"
    else:
        delta_checkpoint = Path(args.delta_checkpoint).expanduser().resolve()

    densepose_script = project_root / "tools" / "make_animal_densepose.py"
    gsam_script = project_root / "tools" / "make_pet_gsam_masks.py"
    refine_script = project_root / "tools" / "refine_pet_agnostic_mask.py"
    inference_script = idm_dir / "inference_pet_delta.py"

    sam_checkpoint = project_root / "checkpoints" / "sam_vit_b_01ec64.pth"
    densepose_config = (
        project_root
        / "detectron2"
        / "projects"
        / "DensePose"
        / "configs"
        / "cse"
        / "densepose_rcnn_R_50_FPN_soft_animals_I0_finetune_16k.yaml"
    )
    densepose_weights = (
        "https://dl.fbaipublicfiles.com/densepose/cse/"
        "densepose_rcnn_R_50_FPN_soft_animals_I0_finetune_16k/"
        "270727112/model_final_421d28.pkl"
    )

    required_paths = [
        densepose_script,
        gsam_script,
        refine_script,
        inference_script,
        sam_checkpoint,
        densepose_config,
        delta_checkpoint / "unet_trainable_delta" / "trainable_delta.safetensors",
    ]

    for p in required_paths:
        if not p.exists():
            raise FileNotFoundError(f"Required path not found: {p}")

    job_id = uuid.uuid4().hex[:12]
    job_root = project_root / "runtime" / "jobs" / job_id

    raw_pet_dir = job_root / "raw_pet_images"
    raw_cloth_dir = job_root / "raw_cloth_images"
    processed_dir = job_root / "processed"
    dataset_dir = job_root / "dataset"
    infer_output_dir = job_root / "infer_output"

    raw_pet_dir.mkdir(parents=True, exist_ok=True)
    raw_cloth_dir.mkdir(parents=True, exist_ok=True)

    image_name = "sample.jpg"
    stem = "sample"

    raw_pet = raw_pet_dir / image_name
    raw_cloth = raw_cloth_dir / image_name

    ensure_rgb_jpg(Path(args.pet_image), raw_pet)
    ensure_rgb_jpg(Path(args.cloth_image), raw_cloth)

    # 1. DensePose-CSE 생성
    pose_dir = processed_dir / "image-densepose"
    run_cmd(
        [
            sys.executable,
            str(densepose_script),
            "--input_dir",
            str(raw_pet_dir),
            "--output_dir",
            str(pose_dir),
            "--config_file",
            str(densepose_config),
            "--weights",
            densepose_weights,
            "--score_thresh",
            "0.3",
            "--width",
            str(IMAGE_SIZE[0]),
            "--height",
            str(IMAGE_SIZE[1]),
        ],
        cwd=project_root,
    )

    # 2. Grounded-SAM 기본 마스크 생성
    mask_base_dir = processed_dir / "agnostic-mask"
    preview_base_dir = processed_dir / "agnostic-preview"

    run_cmd(
        [
            sys.executable,
            str(gsam_script),
            "--input_dir",
            str(raw_pet_dir),
            "--output_dir",
            str(mask_base_dir),
            "--preview_dir",
            str(preview_base_dir),
            "--pet_type",
            args.pet_type,
            "--sam_checkpoint",
            str(sam_checkpoint),
            "--sam_model_type",
            "vit_b",
            "--width",
            str(IMAGE_SIZE[0]),
            "--height",
            str(IMAGE_SIZE[1]),
            "--box_threshold",
            "0.30",
            "--text_threshold",
            "0.25",
            "--mask_mode",
            "full",
            "--dilate_kernel",
            "5",
            "--dilate_iter",
            "1",
        ],
        cwd=project_root,
    )

    # 3. refined mask 생성
    mask_refined_dir = processed_dir / "agnostic-mask-refined"
    preview_refined_dir = processed_dir / "agnostic-preview-refined"

    run_cmd(
        [
            sys.executable,
            str(refine_script),
            "--input_dir",
            str(raw_pet_dir),
            "--base_mask_dir",
            str(mask_base_dir),
            "--output_dir",
            str(mask_refined_dir),
            "--preview_dir",
            str(preview_refined_dir),
            "--pet_type",
            args.pet_type,
            "--sam_checkpoint",
            str(sam_checkpoint),
            "--sam_model_type",
            "vit_b",
            "--width",
            str(IMAGE_SIZE[0]),
            "--height",
            str(IMAGE_SIZE[1]),
            "--part_box_threshold",
            "0.20",
            "--part_text_threshold",
            "0.20",
            "--exclude_dilate_kernel",
            "15",
            "--bottom_cut_ratio",
            "0.28",
            "--top_cut_ratio",
            "0.02",
            "--side_cut_ratio",
            "0.02",
            "--final_dilate_kernel",
            "5",
        ],
        cwd=project_root,
    )

    # 4. inference dataset 구성
    test_dir = dataset_dir / "test"
    image_dir = test_dir / "image"
    cloth_dir = test_dir / "cloth"
    densepose_dir = test_dir / "image-densepose"
    mask_dir = test_dir / "agnostic-mask"

    image_dir.mkdir(parents=True, exist_ok=True)
    cloth_dir.mkdir(parents=True, exist_ok=True)
    densepose_dir.mkdir(parents=True, exist_ok=True)
    mask_dir.mkdir(parents=True, exist_ok=True)

    ensure_rgb_jpg(raw_pet, image_dir / image_name, resize_to=IMAGE_SIZE)
    ensure_rgb_jpg(raw_cloth, cloth_dir / image_name, resize_to=IMAGE_SIZE)

    pose_src = find_first_existing(
        [
            pose_dir / f"{stem}.jpg",
            pose_dir / f"{stem}.png",
        ]
    )
    if pose_src is None:
        raise FileNotFoundError(f"DensePose output not found in: {pose_dir}")

    ensure_rgb_jpg(pose_src, densepose_dir / image_name, resize_to=IMAGE_SIZE)

    mask_src = find_first_existing(
        [
            mask_refined_dir / f"{stem}_mask.png",
            mask_refined_dir / f"{stem}.png",
            mask_base_dir / f"{stem}_mask.png",
            mask_base_dir / f"{stem}.png",
        ]
    )
    if mask_src is None:
        raise FileNotFoundError(f"Mask output not found in: {mask_refined_dir} or {mask_base_dir}")

    ensure_mask_png(mask_src, mask_dir / f"{stem}_mask.png", resize_to=IMAGE_SIZE)

    # pair 파일
    (dataset_dir / "test_pairs.txt").write_text(f"{image_name} {image_name}\n", encoding="utf-8")

    # tagged json
    write_test_json(test_dir / "vitonhd_test_tagged.json", image_name, args.item_name)

    # 5. IDM-VTON delta inference 실행
    infer_output_dir.mkdir(parents=True, exist_ok=True)
    run_cmd(
        [
            sys.executable,
            str(inference_script),
            "--pretrained_model_name_or_path",
            "yisol/IDM-VTON",
            "--finetuned_delta_path",
            str(delta_checkpoint),
            "--data_dir",
            str(dataset_dir),
            "--output_dir",
            str(infer_output_dir),
            "--width",
            str(IMAGE_SIZE[0]),
            "--height",
            str(IMAGE_SIZE[1]),
            "--num_inference_steps",
            str(args.num_inference_steps),
            "--test_batch_size",
            "1",
            "--guidance_scale",
            str(args.guidance_scale),
            "--mixed_precision",
            "fp16",
            "--seed",
            str(args.seed),
        ],
        cwd=idm_dir,
    )

    result_candidates = list(infer_output_dir.glob("*.jpg")) + list(infer_output_dir.glob("*.png"))
    if not result_candidates:
        raise FileNotFoundError(f"No inference result found in: {infer_output_dir}")

    result_path = result_candidates[0]
    output_path = Path(args.output).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # 6. 품질 게이트 + NanoBanana API refinement (optional)
    usage = NanoBananaUsage(mode="local_pipeline_plus_refine")

    if args.use_nanobanana:
        nanobanana_output = job_root / "nanobanana_output" / "refined.jpg"
        nanobanana_output.parent.mkdir(parents=True, exist_ok=True)

        # 6-a. 입력 검증 게이트: 마스크 품질로 API 호출 여부 사전 판단
        viable, viability_reason = evaluate_input_viability(str(mask_src))
        if not viable:
            print(f"\n[QUALITY GATE] REJECT: {viability_reason}")
            print("[QUALITY GATE] NanoBanana API 호출 차단 → 비용 $0")
            usage.mode = "local_pipeline_rejected"
            shutil.copy2(result_path, output_path)
        else:
            # 6-b. 품질 게이트: IDM-VTON 결과 분석
            print("\n[QUALITY GATE] IDM-VTON 결과 품질 분석 중...")
            quality = evaluate_quality(
                result_image_path=str(result_path),
                mask_path=str(mask_src),
                cloth_image_path=str(raw_cloth),
                pet_image_path=str(raw_pet),
            )

            gate_log = quality.to_dict()
            gate_log_path = job_root / "quality_gate_report.json"
            gate_log_path.write_text(json.dumps(gate_log, indent=2, ensure_ascii=False), encoding="utf-8")
            print(f"[QUALITY GATE] {quality.decision.value} (score={quality.score:.2f})")
            for r in quality.reasons:
                print(f"  - {r}")

            if quality.decision == GateDecision.SKIP:
                # 품질 충분 → NanoBanana 호출 불필요
                print("[QUALITY GATE] IDM-VTON 결과 품질 충분 → NanoBanana 스킵 (비용 $0)")
                shutil.copy2(result_path, output_path)

            elif quality.decision == GateDecision.REJECT:
                # 입력 불량 → API 호출 차단
                print("[QUALITY GATE] 입력 품질 불량 → NanoBanana 호출 차단 (비용 $0)")
                usage.mode = "local_pipeline_rejected"
                shutil.copy2(result_path, output_path)

            elif quality.decision == GateDecision.REFINE:
                # 보정 필요 → NanoBanana 1회 호출
                if args.nanobanana_dry_run:
                    print("[NANOBANANA] dry-run: 리파인 필요 판정, 비용 시뮬레이션")
                    simulate_refine(usage)
                    shutil.copy2(result_path, output_path)
                else:
                    # 마스크 정보 기반 스마트 프롬프트 생성
                    smart_prompt = args.nanobanana_prompt or _build_smart_prompt(quality)
                    print(f"[NANOBANANA] 마스크 기반 스마트 프롬프트로 리파인 (1회 호출)...")
                    refine_with_nanobanana(
                        idm_vton_result_path=str(result_path),
                        pet_image_path=str(raw_pet),
                        cloth_image_path=str(raw_cloth),
                        output_path=str(nanobanana_output),
                        prompt=smart_prompt,
                        usage=usage,
                    )
                    shutil.copy2(nanobanana_output, output_path)

        cost_log = usage.summary()
        cost_log["quality_gate"] = gate_log if viable and 'quality' in dir() else {"skipped": viability_reason}
        cost_log_path = job_root / "nanobanana_usage.json"
        cost_log_path.write_text(json.dumps(cost_log, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"\n[NANOBANANA] usage: {json.dumps(cost_log, indent=2)}")
    else:
        shutil.copy2(result_path, output_path)

    print("\n[DONE]")
    print(f"job_id: {job_id}")
    print(f"result: {output_path}")
    print(f"job_root: {job_root}")


if __name__ == "__main__":
    main()
